name: Github Actions pratice

on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "excuting first step"

      - name: github 저장 변수 사용
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

          